#!/bin/bash

if [ $1 == "remove" ]; then

	ldconfig 1>/dev/null 2>/dev/null >/dev/null

	if [ -f "/tmp/startxbmc" ]; then
		/etc/init.d/xbmc start 1>/dev/null 2>/dev/null >/dev/null
		rm /tmp/startxbmc
	fi

fi
