#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	if [ $(pgrep xbmc.bin | wc -l) -eq 1 ]; then
		/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null
		touch /tmp/startxbmc
	fi

	if [ ! -d "/usr/local/bin" ]; then
		mkdir -p "/usr/local/bin";
	fi

	if [ ! -d "/usr/local/include/libcec" ]; then
		mkdir -p "/usr/local/include/libcec";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi

	if [ ! -d "/usr/local/lib/pkgconfig" ]; then
		mkdir -p "/usr/local/lib/pkgconfig";
	fi

fi
